# Generated by Django 5.0.4 on 2024-04-28 22:30

import cpf_field.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="cpf",
        ),
        migrations.AlterField(
            model_name="customuser",
            name="password",
            field=models.CharField(default="", max_length=150),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="username",
            field=cpf_field.models.CPFField(
                help_text="Informe o CPF sem pontos ou traços",
                max_length=14,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
