# Generated by Django 5.0.4 on 2024-04-29 04:27

import cpf_field.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("usuarios", "0002_remove_customuser_cpf_alter_customuser_password_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="username",
            field=cpf_field.models.CPFField(
                default="00000000000",
                help_text="Informe o CPF sem pontos ou traços",
                max_length=14,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
