# Generated by Django 5.0.4 on 2024-05-08 22:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("usuarios", "0003_alter_customuser_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="cargo",
            field=models.CharField(
                choices=[("G", "gestor"), ("A", "aluno")], default="", max_length=1
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="turma",
            field=models.CharField(max_length=30),
        ),
    ]
